exp_name: default_experiment
project_name: default_config
checkpoint_dir: ./runs
comment: Experiment comment goes here

data:
  images_dir: "data/beluga-440"
  train_anno_path: "data/beluga-coco-v0-full/instances_train2023.json"
  val_anno_path: "data/beluga-coco-v0-full/instances_val2023.json"
  viewpoint_list: ['up']
  train_n_filter_min: 4
  val_n_filter_min: 2
  train_n_subsample_max: null
  val_n_subsample_max: 10
  name_keys: ['name', 'viewpoint']
  crop_bbox: False
  image_size:
    - 440
    - 440

engine:
  num_workers: 0
  train_batch_size: 6
  valid_batch_size: 12
  epochs: 30
  seed: 42
  device: cuda
  loss_module: arcface
  use_wandb: false

scheduler_params:
  lr_start: 1.e-5
  lr_max: 1.e-3
  lr_min: 9.e-6
  lr_ramp_ep: 15
  lr_sus_ep: 0
  lr_decay: 0.8
model_params:
  model_name: efficientnetv2_rw_m
  use_fc: false
  fc_dim: 2048
  dropout: 0.0
  loss_module: arcface
  s: 30.0
  margin: 0.50
  ls_eps: 0.0
  theta_zero: 0.785
  pretrained: true
  n_classes: 273 # used for loading checkpoint
test:
  fliplr: false
  fliplr_view: []
  batch_size: 8