exp_name: default_experiment
project_name: default_config
checkpoint_dir: ./runs
comment: Experiment comment goes here
data:
  images_dir: null
  use_full_image_path: true
  viewpoint_list: null
  name_keys: ['id_x']
  crop_bbox: false
  image_size:
    - 256
    - 256
  test:
    anno_path: /mnt/space/space-home/wild-me/multi-species/splits/EDA-single-species-1/instances_val2023.json
    checkpoint_path: ''
    eval_groups:
    - species
    n_filter_min: 1
    n_subsample_max: 10
  train:
    anno_path: /mnt/space/space-home/wild-me/multi-species/splits/EDA-single-species-1/instances_train2023.json
    n_filter_min: 1
    n_subsample_max: null
  val:
    anno_path: /mnt/space/space-home/wild-me/multi-species/splits/EDA-single-species-1/instances_val2023.json
    n_filter_min: 1
    n_subsample_max: 10

engine:
  num_workers: 8
  train_batch_size: 6
  valid_batch_size: 12
  epochs: 30
  seed: 42
  device: cuda
  use_wandb: false

scheduler_params:
  lr_start: 1.e-5
  lr_max: 1.e-3
  lr_min: 9.e-6
  lr_ramp_ep: 15
  lr_sus_ep: 0
  lr_decay: 0.8

model_params:
  model_name: efficientnetv2_rw_m
  use_fc: false
  fc_dim: 2048
  dropout: 0.0
  loss_module: arcface
  s: 30.0
  margin: 0.50
  ls_eps: 0.0
  theta_zero: 0.785
  pretrained: true
  n_classes: 865 
  fliplr: false
  fliplr_view: []
  batch_size: 8